### ISSUE TITLE
daangn-client 무중단 배포 적용 스크립트 작업

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-client#91]
## 작업 내용

- daangn-daangn 프로젝트를 무중단 배포할 수 있도록 `daangn-client`에 `blue/green` 방식 무중단 배포 적용
  - daangn-client를 도커 환경에서 배포할 수 있도록 `aws CodeDeploy`, `git-action`, 도커 관련 설정 적용
- 여기서 정의한 무중단 배포 방식은 1대의 서버 내에서 `nginx reload`를 사용하여 `blue/green` 인스턴스 반환 

## PR

- #92 
- #102 

## 목차

1. 전체 CI/CD 형상
1. CI 툴로 git-action 적용
1. appspec.yml
1. deploy.sh
1. docker-compose.blue.yml & docker-compose.green.yml

---

## 전체 CI/CD 형상

![프로젝트 아키텍쳐 generator 001](https://user-images.githubusercontent.com/75410527/180984260-b34f3053-50e9-4350-aad3-2e82a0687625.jpeg)

## CI 툴로 git-action 적용

- `git-action` 역할
  - `gradle build` 후 프로젝트 파일 압축하여 S3로 전송 및 CodeDeploy Run

```yml
# .github/workflows/deploy.yml

name: daangn-client

on:
  workflow_dispatch: # 수동으로 해당 workflow를 실행시키겠다는 뜻

env: # 현재 스크립트에서 사용할 환경변수 정의
  S3_BUCKET_NAME: cotchan-service-deploy
  PROJECT_NAME: daangn-client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # 깃헙이 제공하는 워크스페이스 (이 workflow 를 실행하는 공간) 에서 내 저장소가 위치한 곳으로 이동
        uses: actions/checkout@v3

      - name: create env file # 깃헙 settings > secrets 에 올려놓은 비밀 값을 복사해 .env.production 파일로 생성
        run: |
          touch .env.production
          echo "${{ secrets.ENV_PROD_VARS }}" >> .env.production

      - name: Set up NPM 16 # npm 셋업
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: npm install
        run: npm install --legacy-peer-deps
        shell: bash

      - name: Build with npm # 프로젝트 build
        run: npm run build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name sandbox-client-service-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name sandbox --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
```

## appspec.yml

- Code Deploy Agent가 배포완료 시 아래 yml에 정의한대로 빌드 스크립트 실행

```yml
version: 0.0
os: linux
files:
  - source: / # 현재 프로젝트의 루트 경로
    destination: /home/ubuntu/daangn-client/ # S3에서 받아올 프로젝트의 위치를 지정 (EC2 내부의 어떤 디렉토리에 전달 ?)
    overwrite: yes # 덮어쓰기 할 것인지?

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks: # CodeDeploy의 배포에는 각 단계 별 수명 주기가 있는데, 수명 주기에 따라 원하는 스크립트를 수행가능
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ubuntu
```

## deploy.sh

- `docker-compose`를 사용하여 `blue/green` 배포 방식을 적용

```bash
#!/bin/bash

ABSPATH=$(readlink -f $0) # 현재 파일 위치 절대 경로로 받기
ABSDIR=$(dirname $ABSPATH) # 현재 디렉토리 위치 
SOURCE_REPOSITORY=$(dirname $ABSDIR) # 부모 디렉토리 위치 
DOCKER_APP_NAME=daangn-client # DOCKER_APP_NAME에는 프로젝트명을 적는다.

# Blue 를 기준으로 현재 떠있는 컨테이너를 한다.
EXIST_BLUE=$(docker-compose -p ${DOCKER_APP_NAME}-blue -f ${SOURCE_REPOSITORY}/docker-compose.blue.yml ps | grep Up)

# 컨테이너 스위칭
if [ -z "$EXIST_BLUE" ]; then
    echo "blue up"
    docker-compose -p ${DOCKER_APP_NAME}-blue -f ${SOURCE_REPOSITORY}/docker-compose.blue.yml up --build -d
    BEFORE_COMPOSE_COLOR="green"
    AFTER_COMPOSE_COLOR="blue"
else
    echo "green up"
    docker-compose -p ${DOCKER_APP_NAME}-green -f ${SOURCE_REPOSITORY}/docker-compose.green.yml up --build -d
    BEFORE_COMPOSE_COLOR="blue"
    AFTER_COMPOSE_COLOR="green"
fi

sleep 10

# 새로운 컨테이너가 제대로 떴는지 확인
EXIST_AFTER=$(docker-compose -p ${DOCKER_APP_NAME}-${AFTER_COMPOSE_COLOR} -f ${SOURCE_REPOSITORY}/docker-compose.${AFTER_COMPOSE_COLOR}.yml ps | grep Up)
if [ -n "$EXIST_AFTER" ]; then
    echo "nginx reload.."
    # nginx.config를 컨테이너에 맞게 변경해주고 reload 한다
    sudo cp ${SOURCE_REPOSITORY}/nginx/service-url-${AFTER_COMPOSE_COLOR}.inc /etc/nginx/conf.d/frontend-url.inc
    sudo systemctl reload nginx

    # 이전 컨테이너 종료
    echo "$BEFORE_COMPOSE_COLOR down"
    docker-compose -p ${DOCKER_APP_NAME}-${BEFORE_COMPOSE_COLOR} -f ${SOURCE_REPOSITORY}/docker-compose.${BEFORE_COMPOSE_COLOR}.yml down
else
    echo "> The new container did not run properly."
    exit 1
fi
```

## docker-compose.blue.yml & docker-compose.green.yml

- blue & green 배포를 위해 docker-compose.yml 파일 2개 정의
- 두 파일은 외부에 개방하는 포트정보만 다를 뿐 나머지 정보는 동일

docker-compose.blue.yml

```yml
version: "3"

services:
  frontend:
    container_name: daangn-client-blue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    # 볼륨을 설정합니다.
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # 리액트 애플리케이션에서 발생하는 버그 해결
    stdin_open: true

networks:
  default:
    external:
      name: daangn_net
```

docker-compose.green.yml

```yml
version: "3"

services:
  frontend:
    container_name: daangn-client-green
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    # 볼륨을 설정합니다.
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # 리액트 애플리케이션에서 발생하는 버그 해결
    stdin_open: true

networks:
  default:
    external:
      name: daangn_net
```

---

- 참고
  - [npm install `--force` and `--legacy-peer-deps` 차이점](https://velog.io/@yonyas/Fix-the-upstream-dependency-conflict-installing-NPM-packages-%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0%EA%B8%B0) 
  - [Disable ESLint that create-react-app provides](https://stackoverflow.com/questions/55821078/disable-eslint-that-create-react-app-provides)
